sudo: required
services:
  - docker
language: php
php:
  - '7.0'
before_install:
  - pecl install mongodb
install:
  - make bootstrap
before_script:
  - ./scripts/travis-setup.sh
script:
  - make tests
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
    - MONGO_HOST=127.0.0.1
    - secure: T29eigdGW102LQzBHoBxQieSw07hCEJ+quFh6SY2kIHEuLy5AzPl4e5/9/7Yi/I/pcQziHlv/zXoH2DB61Wtu+QSDM0ctX24On8LwYjXOlVquZC4eTnzhNlyI0C18kjWaUyeSqWmN0+dJTA3IvYTxe5nKRyfkJrazDbUejUCCpW6iUWIkGpmtG9Vao8iwQON5ZKht6uthGvxVwn7RRNBfg1eKOO7ZbSNoEphEAKUeMRs76P778dsYMd79kBcUagXWki3h0iEBIC8eXKYo8Si9XZVZ6vTfuNSIISOfvRLski7FIJXZs7y5hdYhXIrelvCSUeDY/inqMoevu3rlFRq8Si6sMXqUzkutfFzd5aiPXc5GbfCXjyoM2L9mXIX0AvshYUqmMll+jK86C7DgUSGmMVeS8VYeY7ZuLDJWSL1BE/VwzT0QtVVMNcgcXCS1sWMOtZVlABWuJKp81StOpKqnF0B30kbphFqsbBmOAngwoxB6Yepshd3uVpLYTEOOUyO46rI4rWEBEJlyio/0cwmTatRAQ1Gd9ddNEUV9OVB6rYv5BcArNRfhzTREbEpfDr31154+bAhhk+xQl5ZWIdHLGaxUcaBJitV73WL+DfQgKpNJrueugtKgHUUYdL3HRevvYz1/vFNa/PHXyhNiV3U5JhzBKfUp3pQuvia8B9acL4=
    - secure: OkLImbRuA3lffTLaYUzCoY5qPctpKJQP39flziy1TmJq0fZi7WIOsjOSZVXVOoCwI11FkDWdXZGbfP0cxquotP3mNsC0If9T23ZqEgboyUDk0l05EfbjeH6TLL1MUtA7Ybg993VtQZpQxfxS5E66lqRvHoPen6KSpee8N4celDzzDeruFiZFss0Ttc81k64g2iOz43OcQ7lUVT1EocT9YPB/m2n1aUsiBChVAGMYcgIvWPc4EvKULLJakDdDfraFtqhlMN7EUY0PK5/FndMfooDR258op5xaN0fTo7xsAVKxSeUKdEPSek6I/UKTWqTEb0HTeHEB40N0cCxgYBOEeKsm2lDeXl2B9bVNUUETevvcIl6zwmGkS/M9/d4TUFuwOfnk+PPCzIo1jmYxxxmna1GMjGaUfhlVThahuR+f2pPYpgCojtst/M18ecA6CGUZ5QlL6UPSDL49NZlo7FIqD8V3i59BmpwrLmjvY6r1zpShPfQ0LcbmiEp05e+D9EjsCX4h5XNnSJzLTu9/zL1pVskmVE+f0+UqWtnPruT0hHrztrg9GOtgkRDazneSj9uhD7oZnVmOojDpgWMdAxx8LCg0wSmHaoiEDoayqbj97dScCYM9Dk5JWK6TrfFKwypU/Zy83k7evoyFTtHXSQHIbCt/J/cRy+D6VTiPKRh1HCk=
    - secure: QK1b8/xezk/+Ewhghk0iZJ/a04OlCIQufinG5r8vfbvz13GNoIhCnjTpGZ+ycqgA5oXUPUrMKI4SjdW7hvQq1fRBjbEgqj2/doCJouiHug4h06ldbwZ9v73rMhBjbi/V2cbXn4PFVTSKBiuog0LUsgbHMjPAObR9BBJUUsiCBXIr0O3HhLKwF1hNj+5np8JnRMtUD5fBaUTFAlXOv2gWA5ChiXDA6J5QMD56elfk1G8XaBGSncyzbTHkzHMXxoJkvSOlj2mNlVWcC7pJnK9TeIUzaqXk34mCavmxLNwuUMzhPddDcTNyuIqWNFoxjPUTK9O+5x72HBNKB3WmRAOD+n/zIpoxcYOBRtaL/UblVQF1tmuJ21xQaB+1jVbKJB9QlYYmpmnJkX5GVplNYXrNethJLgVIs/2tJLZtpr49m64LGxRr9Cb7sHQyzLliYXxOGZH/w/yZdYAWzzFS0EM8qMzziBHshhYLiuJSezFtU7R9ETtZKISW0JDF+9jH3wo+jZpE/ewZGn4mFFNl8x7hn/25LXTWE2+ePhMMrAc2f8VC/8HKXBHCrAw3DKtopfIFDQl/V/VYFw9oAuDy1n2j4jr24/3mQXrQ5bWky4hVy8lsB3Uq3MpwNs2plFUafe6Ec0azzeUn21Bv4Rxyy2vUgOY2oHLxJrGTyoXJa8xqBJc=
    - secure: F86RO2hyoyMRFUe9TKA8CMLwkQCXd+7MprkGBTjo1jvvzwDoYi1A05QbAbHaJzrAaXaYykMlOxGPJimHuQtXVBeXnRy8eiqPHyB+Mt8oP3stRYg3wAlfecU91/s/jeL5npIX1RU1vqUg1f09tnU4CVSWLo7/J/ZbfBwoH4YLlhlF76ZKSn9DpKSnPOUA/ofwSiEG0v4NgyzjkC/Bq0CJs/4ZQ9KaFXEINoHiQCGHdHCG+hyN4z0DQ+GxeRTFKEKCLXa+zWaXxwMWH5477Prf8x3GHB1UiXSChuB1yGfDr4kCQxxmbHL3SqyIq+m9ncWDOz6MBcQWTwOAtvZR39tXMiYJ62g8G6k67rFaa3PVT8zwi7Bsh327Bdkupo2uYXAC+6CXU5t4jkfW+k1Hll3Y8NdLx1TJ54bMOCLwabJ0jyAjVD55QXtqh433LYSuGE8Yksc99FD/PlLmHV1rdhK7D79gJGq2w2saR14qciRcA29kNj6b0uYePmtOdcvcMwfRiKiUXYcfBezwv41U2d4ZYdUTkaoALs9alKMNAB9MhPsy0DeBP5pSka1k7aXFXiLxH+Bs0JUcmvCsyvHwRuly1SI4fKGSX21qHk650lDPp7hpyiJ35myG8IODeLicWpvhobsQ0e91pxEZzcofzPBEGPTBp/6yXb418OoRPnA9RZQ=
