version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mongo:latest
      - image: circleci/mysql:latest
    environment:
      MONGO_HOST: '127.0.0.1'
      MYSQL_DATABASE: 'reportbook_test'
      MYSQL_HOST: '127.0.0.1'
      MYSQL_USER: 'reportbook-test'
      MYSQL_PASSWORD: 'geheim'
      SELENIUM_IP: '127.0.0.1'
    steps:
      - setup_remote_docker
      - run: make server
      - run: make setup
      - run: make tests
deploy-job:
  wonderland:
    - branch: master
    - run: make deploy
