version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mongo:latest
      - image: circleci/mysql:latest
    environment:
      MONGO_HOST: '127.0.0.1'
      MYSQL_DATABASE: 'reportbook_test'
      MYSQL_HOST: '127.0.0.1'
      MYSQL_USER: 'reportbook-test'
      MYSQL_PASSWORD: 'geheim'
      SELENIUM_IP: '127.0.0.1'
    steps:
      - run: ./scripts/circleci-setup.sh
      - run: make setup
      - run: ./scripts/selenium-setup-circleci.sh
      - run: ./scripts/run-circleci-reportbook.sh
    test:
      override:
        - run: ./scripts/run-tests-circleci.sh
deploy-job:
  wonderland:
    branch: master
    - run: make deploy
    docker:
