version: 2

jobs:
  build:
    docker:
      - image: mysql:latest
      - image: mongo:latest

  environment:
    APPLICATION_ENV: $APPLICATION_ENV
    MONGO_HOST: $MONGO_HOST
    MYSQL_HOST: $MYSQL_HOST
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_USER: $MYSQL_USER
    MYSQL_PASSWORD: $MYSQL_PASSWORD
    MAILGUN_DOMAIN: $MAILGUN_DOMAIN
    MAILGUN_KEY: $MAILGUN_KEY

  steps:
    - checkout
    - run: ./scripts/run-circleci-reportbook.sh
    - run: ./scripts/run-tests-circleci.sh
