version: 2

jobs:
  build:
    machine: true
    environment:
      MYSQL_DATABASE: 'reportbook_test'
      MYSQL_USER: 'reportbook-test'
      MYSQL_PASSWORD: 'geheim'
      MYSQL_ROOT_PASSWORD: 'geheim'
      DOCKER_HOST_IP: '172.17.0.1'
    steps:
      - checkout
      - run: docker-compose up
      - run: docker-compose exec mongo /scripts/intall-composer.sh
      - run: docker-compose exec mongo /scripts/composer install
      - run: docker-compose exec mongo /scripts/setup-mongo-server.sh
      - run: docker-compose exec mysql /scripts/setup-mysql-server.sh
      - run: docker-compose run reportbook scripts/phpunit

deploy-job:
  wonderland:
    - branch: master
    - run: make deploy
