version: 2

jobs:
  build:
    machine: true
    docker:
      - image: mysql:latest
      - image: mongo:latest

    environment:
      MYSQL_DATABASE: 'reportbook_test'
      MYSQL_USER: 'reportbook-test'
      MYSQL_PASSWORD: 'geheim'
      DOCKER_HOST_IP: '172.17.0.1'

    steps:
      - setup_remote_docker
      - checkout
      - run: ./scripts/run-circleci-reportbook.sh
      - run: ./scripts/run-tests-circleci.sh
