'production':
  mongo_server_db:   reportbook_production
'test':
  mongo_username: reportbook-test
  mongo_password: geheim
  mongo_database: reportbook_test
'dev':
  mongo_username: reportbook-dev
  mongo_password: geheim
  mongo_database: reportbook_dev
