'production':
  mongo_database: reportbook
  mongo_host: ds019996.mlab.com
  mongo_port: 19996
  mongo_username: reportbook
  default_profile: /var/www/app/default_profile.jpg
  timezone: Europe/Berlin
  log_path: /var/www/app/log.txt
  papertrail_host: logs2.papertrailapp.com
  papertrail_port: 11559
  papertrail_system: reportbook
  template_path: /var/www/src/Web/Controller/Views
  cache_path: /var/www/src/Web/Cache
  printer_templates: /Templates
  printer_output: /tmp/
  printer_output_type: download
  storage: mongo
'test':
  mongo_username: reportbook-test
  mongo_password: geheim
  mongo_database: reportbook_test
  mongo_port: 27017
  default_profile: app/default_profile.jpg
  log_path: tests/unit/Notification/log.txt
  template_path: /Controller/Views
  cache_path: /var/www/src/Web/Cache
  mysql_database: reportbook_test
  mysql_user: reportbook-test
  mysql_password: geheim
  printer_templates: /Templates
  printer_output: /var/www/tests/functional/Printer/Pdf/
  printer_output_type: file
  storage: mysql
'dev':
  mongo_username: reportbook-dev
  mongo_password: geheim
  mongo_database: reportbook_dev
  mongo_port: 27017
  default_profile: /var/www/app/default_profile.jpg
  timezone: Europe/Berlin
  log_path: /var/www/app/log.txt
  papertrail_host: logs2.papertrailapp.com
  papertrail_port: 11559
  papertrail_system: reportbook_dev
  template_path: /var/www/src/Web/Controller/Views
  cache_path: /var/www/src/Web/Cache
  mysql_database: reportbook_dev
  mysql_user: reportbook-dev
  mysql_password: geheim
  printer_templates: /Templates
  printer_output: /tmp/
  printer_output_type: download
  storage: mysql
  api_token: geheim
