'production':
  mongo_database: reportbook
  mongo_host: ds019996.mlab.com
  mongo_port: 19996
  mongo_username: reportbook
  default_profile: /var/www/app/default_profile.jpg
  timezone: Europe/Berlin
  log_path: app/log.txt
'test':
  mongo_username: reportbook-test
  mongo_password: geheim
  mongo_database: reportbook_test
  mongo_port: 27017
  default_profile: app/default_profile.jpg
  log_path: tests/Notification/log.txt
'dev':
  mongo_username: reportbook-dev
  mongo_password: geheim
  mongo_database: reportbook_dev
  mongo_port: 27017
  default_profile: app/default_profile.jpg
  timezone: Europe/Berlin
  log_path: app/log.txt
