version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "80:80"
    environment:
      - APPLICATION_ENV
      - MAILGUN_DOMAIN
      - MAILGUN_KEY
      - MONGO_HOST=mongo
      - MYSQL_HOST=mysql
    volumes:
      - .:/var/www
    command: ./scripts/circleci/setup.sh
    links:
      - mongo
      - mysql
  mongo:
    image: "mongo:4.0.4"
    ports:
      - "27017:27017"
    volumes:
      - reportbook-data-tests:/data/db
      - ./scripts:/scripts
  mysql:
    image: "mysql:5.7.22"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - reportbook-data-mysql-tests:/var/lib/mysql
      - ./scripts:/scripts
volumes:
  reportbook-data-tests:
  reportbook-data-mysql-tests:
