version: '3'
services:
  reportbook:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "80:80"
    environment:
      - APPLICATION_ENV
      - MAILGUN_DOMAIN
      - MAILGUN_KEY
      - MONGO_HOST=mongo
      - MYSQL_HOST=mysql
    extra_hosts:
      - "docker_host:${DOCKER_HOST_IP}"
    volumes:
      - .:/var/www
    links:
      - mongo
      - mysql
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - reportbook-data:/data/db
      - ./scripts:/scripts
    command: --auth
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - reportbook-data-mysql:/var/lib/mysql
      - ./scripts:/scripts
volumes:
  reportbook-data:
  reportbook-data-mysql:
