version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "80:80"
    environment:
      - APPLICATION_ENV=test
      - MAILGUN_DOMAIN
      - MAILGUN_KEY
      - MONGO_HOST=mongo
      - MYSQL_HOST=mysql
      - DOCKER_IP
    volumes:
      - .:/var/www
    command: >
      ./scripts/circleci/setup.sh
      ./scripts/phpunit
    links:
      - mongo
      - mysql
    container_name: reportbook-test
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - reportbook-data-tests:/data/db
      - ./scripts:/scripts
    command: --auth
  mysql:
    image: "mysql:5.7.22"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - reportbook-data-mysql-tests:/var/lib/mysql
      - ./scripts:/scripts
volumes:
  reportbook-data-tests:
  reportbook-data-mysql-tests:
