version: 2.1
jobs:
  build:
    machine:
      enabled: true

    steps:
      - checkout
      - run: docker-compose -f docker-compose-circleci.yml up -d
      - run: docker-compose -f docker-compose-circleci.yml run tests
