CREATE USER IF NOT EXISTS 'MYSQL_USER'@'localhost' IDENTIFIED BY 'MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_USER'@'localhost' WITH GRANT OPTION;
REVOKE CREATE USER, SUPER ON *.* FROM 'MYSQL_USER'@'localhost';
